# Generated by Django 4.1.4 on 2022-12-19 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='osteo/images', validators=[django.core.validators.validate_image_file_extension], verbose_name='images')),
            ],
        ),
    ]
